language : php
php : 
	- '7.0.25'
	- hhvm # on Trustly Only
	- nightly

before_script : composer require atoum/atoum
script : vendor/bin/atoum
install : php vendor/vendors.php
install : 
  - .bin/ci//install_dependencies.sh
  - php vendor/vendors.php

install : composer